# Generated by Django 2.2 on 2019-09-14 02:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='authors',
            field=models.ManyToManyField(related_name='writable_feeds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feed',
            name='publishers',
            field=models.ManyToManyField(related_name='publishable_feeds', to=settings.AUTH_USER_MODEL),
        ),
    ]
