# Generated by Django 2.2 on 2019-09-14 02:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190914_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='mtime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
